name: pso
description: Particle Swarm Optimization tool for Dart. The implementation supposes the objective function is a maximation and optimization parameters are customizable.
version: 1.0.3
homepage: https://github.com/jbytecode/pso

environment:
  sdk: '>=3.0.0 <4.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
